require('plugin-configs.telescope')
require('plugin-configs.lualine')
require('plugin-configs.lspconf')
require('plugin-configs.mini')
require('plugin-configs.autopairs')
require('plugin-configs.git')
require('plugin-configs.indentguides')
require('plugin-configs.mason')
require('plugin-configs.nvim-tree')
require('plugin-configs.docs-view')
require('plugin-configs.treesitter')
require('plugin-configs.bookmarks')
require('plugin-configs.ale')

require('maps')
